name: matsci465
channels:
  - defaults
  - conda-forge
dependencies:
  - anyio=4.10.0=py310hca03da5_0
  - aom=3.12.1=ha237518_0
  - appnope=0.1.4=py310hca03da5_0
  - argon2-cffi=25.1.0=py310hca03da5_0
  - argon2-cffi-bindings=25.1.0=py310h254cc4a_0
  - arrow-cpp=21.0.0=h9e9184e_1
  - asttokens=3.0.0=py310hca03da5_0
  - async-lru=2.0.5=py310hca03da5_0
  - attrs=25.4.0=py310hca03da5_2
  - aws-c-auth=0.9.0=h79febb2_2
  - aws-c-cal=0.9.2=hd08b81e_1
  - aws-c-common=0.12.4=h6caf38d_0
  - aws-c-compression=0.3.1=habbe1e8_6
  - aws-c-event-stream=0.5.6=hd40f934_1
  - aws-c-http=0.10.4=he148155_1
  - aws-c-io=0.21.4=h89d1e94_1
  - aws-c-mqtt=0.13.3=h8d8bef9_4
  - aws-c-s3=0.8.7=h79febb2_0
  - aws-c-sdkutils=0.2.4=habbe1e8_1
  - aws-checksums=0.2.7=habbe1e8_2
  - aws-crt-cpp=0.34.0=hee39554_0
  - aws-sdk-cpp=1.11.638=h35fa3df_0
  - babel=2.17.0=py310hca03da5_0
  - beautifulsoup4=4.14.2=py310hca03da5_0
  - blas=1.0=openblas
  - bleach=6.3.0=py310hca03da5_0
  - blosc=1.21.6=h5499902_0
  - bokeh=3.8.1=pyhd8ed1ab_0
  - brotli=1.0.9=h1a8c8d9_9
  - brotli-bin=1.0.9=h1a8c8d9_9
  - brotlicffi=1.2.0.0=py310h50f4ffc_0
  - brunsli=0.1=h9f76cd9_0
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.34.6=hc919400_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h191e429_0
  - certifi=2026.01.04=py310hca03da5_0
  - cffi=2.0.0=py310h73c2a22_1
  - cfitsio=4.6.2=h7200ff5_1
  - charls=2.4.2=h13dd4ca_0
  - charset-normalizer=3.4.4=py310hca03da5_0
  - click=8.3.1=pyh8f84b5b_1
  - cloudpickle=3.1.2=pyhcf101f3_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - colorspacious=1.1.2=pyhecae5ae_1
  - comm=0.2.3=py310hca03da5_0
  - contourpy=1.3.1=py310h48ca7d4_0
  - cpython=3.10.19=py310hd8ed1ab_2
  - cycler=0.12.1=py310hca03da5_0
  - cyrus-sasl=2.1.28=ha1cbb27_0
  - cytoolz=1.1.0=py310hfe3a0ae_1
  - dask=2025.12.0=pyhcf101f3_0
  - dask-core=2025.12.0=pyhcf101f3_1
  - dask-image=2025.11.0=pyhd8ed1ab_0
  - dav1d=1.2.1=h80987f9_0
  - debugpy=1.8.16=py310h50f4ffc_1
  - decorator=5.2.1=py310hca03da5_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - dill=0.4.0=pyhcf101f3_1
  - distributed=2025.12.0=pyhcf101f3_1
  - emdfile=0.0.16=pyhd8ed1ab_1
  - exceptiongroup=1.3.0=py310hca03da5_0
  - executing=2.2.1=py310hca03da5_0
  - expat=2.7.3=h50f4ffc_4
  - filelock=3.20.2=pyhd8ed1ab_0
  - flexcache=0.3=pyhd8ed1ab_1
  - flexparser=0.4=pyhd8ed1ab_1
  - fontconfig=2.15.0=h29935d0_0
  - fonttools=4.61.0=py310haa24f5a_0
  - freetype=2.13.3=h47d26ad_0
  - fribidi=1.0.10=h1a28f6b_0
  - fsspec=2025.12.0=pyhd8ed1ab_0
  - gdown=5.2.0=pyhd8ed1ab_1
  - gettext=0.21.0=hbdbcc25_2
  - gflags=2.2.2=hf9b8971_1005
  - giflib=5.2.2=h93a5062_0
  - glog=0.5.0=h5c6a83d_0
  - gmp=6.3.0=h7bae524_2
  - gmpy2=2.2.1=py310h1b1a8f9_2
  - graphite2=1.3.14=hc377ac9_1
  - gst-plugins-base=1.24.12=hc962c03_1
  - gstreamer=1.24.12=h4a1bc71_1
  - gstreamer-orc=0.4.41=h4a9b20c_0
  - h11=0.16.0=py310hca03da5_1
  - h5py=3.15.1=nompi_py310hc571fcd_101
  - harfbuzz=10.2.0=he637ebf_1
  - hdf5=1.14.6=nompi_hd3baa01_104
  - hdf5plugin=5.1.0=py310h2304afb_1
  - html5lib=1.1=pyhd3eb1b0_0
  - httpcore=1.0.9=py310hca03da5_0
  - httpx=0.28.1=py310hca03da5_1
  - hyperspy=2.3.0=pyhd8ed1ab_3
  - hyperspy-base=2.3.0=pyhd8ed1ab_3
  - hyperspy-gui-ipywidgets=2.1.0=pyhd8ed1ab_0
  - hyperspy-gui-traitsui=2.1.1=pyhd8ed1ab_0
  - icu=73.1=h313beb8_0
  - idna=3.11=py310hca03da5_0
  - imagecodecs=2024.9.22=py310h1c5cdcd_3
  - imageio=2.37.0=pyhfb79c49_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - ipykernel=6.31.0=py310h7eb115d_0
  - ipympl=0.9.8=pyhcf101f3_0
  - ipython=8.30.0=py310hca03da5_0
  - ipython_pygments_lexers=1.1.1=py310hca03da5_0
  - ipywidgets=8.1.7=py310hca03da5_0
  - jedi=0.19.2=py310hca03da5_0
  - jinja2=3.1.6=py310hca03da5_0
  - joblib=1.5.2=py310hca03da5_0
  - jpeg=9f=h2f69dba_0
  - json5=0.12.1=py310hca03da5_0
  - jsonschema=4.25.0=py310hca03da5_1
  - jsonschema-specifications=2025.9.1=py310hca03da5_0
  - jupyter=1.1.1=py310hca03da5_0
  - jupyter-lsp=2.2.5=py310hca03da5_0
  - jupyter_client=8.6.3=py310hca03da5_1
  - jupyter_console=6.6.3=py310hca03da5_0
  - jupyter_core=5.9.1=py310hca03da5_0
  - jupyter_events=0.12.0=py310hca03da5_1
  - jupyter_server=2.17.0=py310hca03da5_0
  - jupyter_server_terminals=0.5.3=py310hca03da5_0
  - jupyterlab=4.5.0=py310hca03da5_0
  - jupyterlab_pygments=0.3.0=py310hca03da5_0
  - jupyterlab_server=2.28.0=py310hca03da5_0
  - jupyterlab_widgets=3.0.15=py310hca03da5_0
  - jxrlib=1.2=h2c76fc5_0
  - kiwisolver=1.4.9=py310haeee614_0
  - krb5=1.21.3=h237132a_0
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lcms2=2.17=h7418793_0
  - lerc=4.0.0=h313beb8_0
  - libabseil=20250127.0=cxx17_h07bc746_0
  - libaec=1.1.4=h51d1e36_0
  - libavif=1.3.0=h839b4eb_0
  - libbrotlicommon=1.0.9=h1a8c8d9_9
  - libbrotlidec=1.0.9=h1a8c8d9_9
  - libbrotlienc=1.0.9=h1a8c8d9_9
  - libclang13=20.1.8=default_h13b06bd_6
  - libcurl=8.18.0=he38603e_0
  - libcxx=20.1.8=hd7fd590_1
  - libdeflate=1.22=h80987f9_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libevent=2.1.12=h2757513_1
  - libexpat=2.7.3=h50f4ffc_4
  - libffi=3.4.4=hca03da5_1
  - libgfortran=15.2.0=h09d7db9_1
  - libgfortran5=15.2.0=hb654fa1_1
  - libglib=2.84.4=h7a3292d_0
  - libgrpc=1.71.0=hf667ad3_0
  - libiconv=1.16=h80987f9_3
  - libkrb5=1.21.3=h73ed823_4
  - libllvm20=20.1.8=h846d351_0
  - libnghttp2=1.67.0=hc438710_0
  - libntlm=1.8=h5505292_0
  - libogg=1.3.5=h48c0fde_1
  - libopenblas=0.3.30=hf2bb037_2
  - libopenjpeg=2.5.4=haa24f5a_1
  - libopus=1.6=he530434_0
  - libpng=1.6.50=h5c318fc_0
  - libpq=17.6=h479fd88_0
  - libprotobuf=5.29.3=hccd9074_0
  - libre2-11=2024.07.02=hd41c47c_3
  - libsodium=1.0.20=h897f8a9_0
  - libsqlite=3.51.1=h1b79a29_1
  - libssh2=1.11.1=h1590b86_0
  - libthrift=0.22.0=h14a376c_1
  - libtiff=4.7.1=h367c460_0
  - libvorbis=1.3.7=h81086ad_2
  - libwebp-base=1.6.0=h92b2d59_0
  - libxml2=2.13.9=h528a072_0
  - libzlib=1.3.1=h5f15de7_0
  - libzopfli=1.0.3=h9f76cd9_0
  - link-traits=1.0.3=pyhd8ed1ab_4
  - llvm-openmp=20.1.8=he822017_0
  - llvmlite=0.44.0=py310h5fad91f_2
  - lmdb=0.9.31=h93a5062_1
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.3.3=py310hc798581_1
  - lz4-c=1.9.4=h313beb8_1
  - markupsafe=3.0.2=py310h80987f9_0
  - matplotlib=3.10.7=py310hca03da5_0
  - matplotlib-base=3.10.7=py310haa222d5_0
  - matplotlib-inline=0.2.1=py310hca03da5_0
  - mistune=3.1.2=py310hca03da5_0
  - mpc=1.3.1=h8f1351a_1
  - mpfr=4.2.1=hb693164_3
  - mpire=2.10.2=pyhd8ed1ab_1
  - mpmath=1.3.0=pyhd8ed1ab_1
  - msgpack-python=1.1.2=py310h0e897d2_1
  - mysql-common=9.3.0=hd7719f6_0
  - mysql-libs=9.3.0=ha8be5b7_0
  - narwhals=2.15.0=pyhcf101f3_0
  - natsort=8.4.0=pyh29332c3_1
  - nbclient=0.10.2=py310hca03da5_0
  - nbconvert=7.16.6=py310hca03da5_0
  - nbconvert-core=7.16.6=py310hca03da5_0
  - nbconvert-pandoc=7.16.6=py310hca03da5_0
  - nbformat=5.10.4=py310hca03da5_0
  - ncempy=1.14=pyhd8ed1ab_0
  - ncurses=6.5=hee39554_0
  - nest-asyncio=1.6.0=py310hca03da5_0
  - networkx=3.4.2=pyh267e887_2
  - notebook=7.5.0=py310hca03da5_0
  - notebook-shim=0.2.4=py310hca03da5_0
  - numba=0.61.2=py310hd3faf9e_1
  - numexpr=2.14.1=py310h2d91af3_1
  - numpy=2.2.5=py310h40d09ce_2
  - numpy-base=2.2.5=py310h855c928_2
  - openjpeg=2.5.4=hbfb3c88_0
  - openldap=2.6.10=hbe55e7a_0
  - openssl=3.6.0=h5503f6c_0
  - orc=2.2.0=hec253e6_0
  - overrides=7.7.0=py310hca03da5_0
  - packaging=25.0=py310hca03da5_1
  - pandas=2.3.3=py310h25f4b65_1
  - pandoc=3.8=hca03da5_0
  - pandocfilters=1.5.1=py310hca03da5_0
  - parso=0.8.5=py310hca03da5_0
  - partd=1.4.2=pyhd8ed1ab_0
  - pcre2=10.46=h1dacb4a_0
  - pentapy=1.4.1=py310hfdc7867_0
  - pexpect=4.9.0=py310hca03da5_1
  - pillow=12.0.0=py310he2d6fe4_1
  - pims=0.7=pyhd8ed1ab_1
  - pint=0.24.4=pyhe01879c_2
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h09dc60e_0
  - platformdirs=4.5.0=py310hca03da5_0
  - ply=3.11=pyhd8ed1ab_3
  - pooch=1.8.2=pyhd8ed1ab_3
  - prettytable=3.17.0=pyhd8ed1ab_0
  - prometheus_client=0.21.1=py310hca03da5_0
  - prompt-toolkit=3.0.52=py310hca03da5_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - psutil=7.0.0=py310haa24f5a_1
  - ptyprocess=0.7.0=pyhd3eb1b0_3
  - pure_eval=0.2.3=py310hca03da5_0
  - py4dstem=0.14.16=pyhd8ed1ab_0
  - pyaml=25.7.0=pyhe01879c_0
  - pyarrow=21.0.0=py310h3f644e9_1
  - pybaselines=1.2.1=pyhd8ed1ab_0
  - pycparser=2.23=py310hca03da5_0
  - pyface=8.0.0=pyhd8ed1ab_2
  - pygments=2.19.2=py310hca03da5_0
  - pylops=2.6.0=pyhd8ed1ab_0
  - pyparsing=3.2.5=py310hca03da5_0
  - pyqt=5.15.4=py310h1105856_0
  - pysocks=1.7.1=py310hca03da5_1
  - python=3.10.15=hdce6c4c_2_cpython
  - python-box=7.3.2=py310hfe3a0ae_1
  - python-dateutil=2.9.0post0=py310hca03da5_2
  - python-fastjsonschema=2.21.2=py310hca03da5_0
  - python-json-logger=4.0.0=py310hca03da5_0
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.10=8_cp310
  - pytz=2025.2=pyhd8ed1ab_0
  - pywavelets=1.8.0=py310hc12b6d3_0
  - pywin32-on-windows=0.1.0=pyh1179c8e_3
  - pyyaml=6.0.3=py310h091b9d3_0
  - pyzmq=27.1.0=py310h5a8c52c_1
  - qt-main=5.15.2=h5e2fe81_13
  - qtconsole=5.7.0=py310hca03da5_0
  - qtpy=2.4.3=py310hca03da5_0
  - re2=2024.07.02=h6589ca4_3
  - readline=8.3=h0b18652_0
  - referencing=0.37.0=py310hca03da5_0
  - requests=2.32.5=py310hca03da5_1
  - rfc3339-validator=0.1.4=py310hca03da5_0
  - rfc3986-validator=0.1.1=py310hca03da5_0
  - rosettasciio-base=0.12.0=py310h72544b6_0
  - rpds-py=0.28.0=py310h931abed_0
  - ruamel.yaml=0.19.1=pyhcf101f3_0
  - ruamel.yaml.clib=0.2.15=py310haea493c_1
  - scikit-image=0.25.2=py310h25f4b65_2
  - scikit-learn=1.4.2=py310h64e73be_1
  - scikit-optimize=0.10.2=pyhd8ed1ab_1
  - scipy=1.15.3=py310h132fc3c_1
  - send2trash=1.8.2=py310hca03da5_1
  - setuptools=80.9.0=py310hca03da5_0
  - sip=6.15.0=py310hc7786af_0
  - six=1.17.0=py310hca03da5_0
  - slicerator=1.1.0=pyhd8ed1ab_1
  - snappy=1.2.2=hada39a4_1
  - sniffio=1.3.1=py310hca03da5_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - soupsieve=2.5=py310hca03da5_0
  - sqlite=3.51.1=hab6afd1_0
  - stack_data=0.6.3=py310hca03da5_0
  - sympy=1.14.0=pyh2585a3b_105
  - tblib=3.2.2=pyhcf101f3_0
  - terminado=0.18.1=py310hca03da5_0
  - threadpoolctl=3.5.0=py310h7eb115d_1
  - tifffile=2024.12.12=pyhd8ed1ab_0
  - tinycss2=1.4.0=py310hca03da5_0
  - tk=8.6.15=hcd8a7d5_0
  - toml=0.10.2=pyhcf101f3_3
  - tomli=2.2.1=py310hca03da5_0
  - toolz=1.1.0=pyhd8ed1ab_1
  - tornado=6.5.4=py310haa24f5a_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=py310hca03da5_0
  - traits=7.1.0=py310hfe3a0ae_0
  - traitsui=8.0.0=pyhd8ed1ab_1
  - typing-extensions=4.15.0=py310hca03da5_0
  - typing_extensions=4.15.0=py310hca03da5_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.6.3=py310hca03da5_0
  - utf8proc=2.6.1=h80987f9_1
  - wcwidth=0.2.14=py310hca03da5_0
  - webencodings=0.5.1=py310hca03da5_1
  - websocket-client=1.8.0=py310hca03da5_0
  - wheel=0.45.1=py310hca03da5_0
  - widgetsnbextension=4.0.14=py310hca03da5_0
  - xyzservices=2025.11.0=pyhd8ed1ab_0
  - xz=5.6.4=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - zeromq=4.3.5=h2c7f8f0_1
  - zfp=1.0.1=ha86207d_5
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=h5f15de7_0
  - zlib-ng=2.0.7=h1a8c8d9_0
  - zstd=1.5.7=h817c040_0
  - pip:
      - absl-py==2.3.1
      - astunparse==1.6.3
      - flatbuffers==25.12.19
      - gast==0.7.0
      - google-pasta==0.2.0
      - grpcio==1.76.0
      - keras==3.12.0
      - libclang==18.1.1
      - markdown==3.10
      - markdown-it-py==4.0.0
      - mdurl==0.1.2
      - ml-dtypes==0.5.4
      - namex==0.1.0
      - opt-einsum==3.4.0
      - optree==0.18.0
      - protobuf==6.33.2
      - pyqt5-sip==12.9.0
      - rich==14.2.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - termcolor==3.3.0
      - werkzeug==3.1.4
      - wrapt==2.0.1
prefix: /Users/kgeis/miniconda3/envs/matsci465
